server:
  port: 8888
---
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hemantjava/git-configuration.git
          searchPaths: config #looking for sub directory